apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-provider-azure-keyvault
spec:
  parameters:
    keyvaultName: vpp-aks-d
    objects: |
      array:
        - |
          objectName: vpp-eneco-com
          objectType: secret
    resourceGroup: rg-vpp-app-sb-401
    subscriptionId: 7b1ba02e-bac6-4c45-83a0-7f0d3104922e
    tenantId: eca36054-49a9-4731-a42f-8400670fc022
    usePodIdentity: 'false'
    useVMManagedIdentity: 'true'
    userAssignedIdentityID: 419ef759-bafa-49c2-b26b-33ae7b073435
  provider: azure
  secretObjects:
    - data:
        - key: tls.key
          objectName: vpp-eneco-com
        - key: tls.crt
          objectName: vpp-eneco-com
      secretName: vpp-eneco-com-tls-certificate
      type: kubernetes.io/tls
