apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.roelvandegrint.com/

  application.instanceLabelKey: argocd.argoproj.io

  # oidc.config: |
  #   name: Azure
  #   issuer: https://login.microsoftonline.com/eca36054-49a9-4731-a42f-8400670fc022/v2.0
  #   clientID: 504b5d75-5397-40e9-9b94-29ddd4eee8be
  #   clientSecret: $oidc.azure.clientSecret
  #   requestedIDTokenClaims:
  #     groups:
  #       essential: true
  #   requestedScopes:
  #     - openid
  #     - profile
  #     - email
